/**
 * Event translation: hermes stdout → Anthropic Managed Agents SSE events.
 *
 * Hermes outputs plain text to stdout (no structured JSON), so every non-empty
 * chunk is a text delta for agent.message. Session lifecycle events (idle/error)
 * are generated by the run-turn logic in index.mjs.
 */

export function translateRuntimeEvent(chunk, { model, messageId, partId, sessionId }) {
  const text = typeof chunk === "string" ? chunk : chunk.toString("utf8");
  if (!text) return null;
  return {
    type: "agent.message",
    properties: {
      sessionID: sessionId,
      id: messageId,
      content: [{ type: "text", text }],
      model: model || "unknown",
      stop_reason: null,
    },
  };
}

export function idleEvent(sessionId) {
  return {
    type: "session.status_idle",
    properties: {
      sessionID: sessionId,
      stop_reason: { type: "end_turn" },
    },
  };
}

export function errorEvent(sessionId, message) {
  return {
    type: "session.error",
    properties: {
      sessionID: sessionId,
      error: { message },
    },
  };
}
